defaults: &defaults
  app_name: Handy Works
  host: localhost:3000
  options:
     sex:
       - 'male'
       - 'female'
     category:
       - 'cat1'
     student:
       - 'test'
     type:
       - 'test'
     married:
       - 'test'
     title:
       - 'Mr'
       - 'Mrs'
       - 'Ms'
     work_status:
       - 'test'
     clinic:
       - 'test'
     referred_by:
       - 'test'
       - 'test'
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
